language: swift
xcode_project: Sample-project-1/Sample-project-1.xcodeproj # path to your xcodeproj folder
xcode_scheme: Sample-project-1
xcode_destination: platform=iOS Simulator,OS=11.3,name=iPhone X